const emojipedia = [
  {
    id: 1,
    emoji: "💪",
    name: "Tense Biceps",
    meaning: "Represents strength, encouragement, or working out.",
  },
  {
    id: 2,
    emoji: "🙏",
    name: "Folded Hands",
    meaning: "Symbolizes prayer, gratitude, or a high five.",
  },
  {
    id: 3,
    emoji: "🤣",
    name: "ROFL",
    meaning: "Represents uncontrollable laughter.",
  },
  {
    id: 4,
    emoji: "😃",
    name: "Grinning Face",
    meaning: "Expresses happiness and friendliness.",
  },
  {
    id: 5,
    emoji: "😢",
    name: "Crying Face",
    meaning: "Indicates sadness or disappointment.",
  },
  {
    id: 6,
    emoji: "❤️",
    name: "Red Heart",
    meaning: "Symbol of love and affection.",
  },
  {
    id: 7,
    emoji: "🔥",
    name: "Fire",
    meaning: "Used to indicate something cool, awesome, or trending.",
  },
  {
    id: 8,
    emoji: "✨",
    name: "Sparkles",
    meaning: "Represents beauty, magic, or excitement.",
  },
  {
    id: 9,
    emoji: "🎉",
    name: "Party Popper",
    meaning: "Symbolizes celebration and joy.",
  },
  {
    id: 10,
    emoji: "💯",
    name: "Hundred Points",
    meaning: "Indicates perfection or strong approval.",
  },
  {
    id: 11,
    emoji: "😎",
    name: "Cool Face",
    meaning: "Represents confidence and swag.",
  },
  {
    id: 12,
    emoji: "😔",
    name: "Pensive Face",
    meaning: "Expresses sadness or deep thought.",
  },
  {
    id: 13,
    emoji: "😇",
    name: "Innocent Face",
    meaning: "Indicates kindness, innocence, or angelic behavior.",
  },
  {
    id: 14,
    emoji: "🤔",
    name: "Thinking Face",
    meaning: "Used when deep in thought or pondering something.",
  },
  {
    id: 15,
    emoji: "😴",
    name: "Sleeping Face",
    meaning: "Represents tiredness or sleepiness.",
  },
  {
    id: 16,
    emoji: "😜",
    name: "Winking Face",
    meaning: "Expresses playfulness or joking.",
  },
  {
    id: 17,
    emoji: "🤗",
    name: "Hugging Face",
    meaning: "Represents warmth, comfort, or a virtual hug.",
  },
  {
    id: 18,
    emoji: "🤩",
    name: "Star-Struck",
    meaning: "Used when excited or in admiration of something.",
  },
  {
    id: 19,
    emoji: "😡",
    name: "Angry Face",
    meaning: "Indicates frustration, annoyance, or rage.",
  },
  {
    id: 20,
    emoji: "😱",
    name: "Screaming Face",
    meaning: "Represents shock, fear, or amazement.",
  },
  {
    id: 21,
    emoji: "😈",
    name: "Smiling Devil",
    meaning: "Suggests mischievous or naughty behavior.",
  },
  {
    id: 22,
    emoji: "💀",
    name: "Skull",
    meaning: "Used to symbolize death or something scary.",
  },
  {
    id: 23,
    emoji: "👻",
    name: "Ghost",
    meaning: "Represents something spooky or playful.",
  },
  {
    id: 24,
    emoji: "🤐",
    name: "Zipper-Mouth",
    meaning: "Used to indicate secrecy or staying quiet.",
  },
  {
    id: 25,
    emoji: "😷",
    name: "Mask Face",
    meaning: "Represents sickness or health concerns.",
  },
  {
    id: 26,
    emoji: "🤒",
    name: "Sick Face",
    meaning: "Used to show feeling unwell.",
  },
  {
    id: 27,
    emoji: "🤕",
    name: "Injured Face",
    meaning: "Indicates physical pain or injury.",
  },
  {
    id: 28,
    emoji: "🤑",
    name: "Money Face",
    meaning: "Used to represent wealth or success.",
  },
  {
    id: 29,
    emoji: "🤯",
    name: "Mind-Blown",
    meaning: "Indicates amazement or shock.",
  },
  {
    id: 30,
    emoji: "🙄",
    name: "Eye Roll",
    meaning: "Expresses annoyance or disbelief.",
  },
  {
    id: 31,
    emoji: "😋",
    name: "Yum Face",
    meaning: "Represents delicious food or satisfaction.",
  },
  {
    id: 32,
    emoji: "🤡",
    name: "Clown Face",
    meaning: "Used to describe someone foolish or goofy.",
  },
  {
    id: 33,
    emoji: "👽",
    name: "Alien",
    meaning: "Represents extraterrestrial beings or something strange.",
  },
  {
    id: 34,
    emoji: "🤖",
    name: "Robot",
    meaning: "Indicates AI, technology, or robotics.",
  },
  {
    id: 35,
    emoji: "🎸",
    name: "Guitar",
    meaning: "Symbolizes music and rock culture.",
  },
  {
    id: 36,
    emoji: "🚀",
    name: "Rocket",
    meaning: "Represents space travel or rapid growth.",
  },
  {
    id: 37,
    emoji: "🌎",
    name: "Globe",
    meaning: "Represents Earth or environmental concerns.",
  },
  {
    id: 38,
    emoji: "⚡",
    name: "Lightning",
    meaning: "Symbolizes energy, power, or sudden impact.",
  },
  {
    id: 39,
    emoji: "🍕",
    name: "Pizza",
    meaning: "Represents food, especially a love for pizza.",
  },
  {
    id: 40,
    emoji: "🌈",
    name: "Rainbow",
    meaning: "Symbolizes diversity, pride, or happiness.",
  },
  {
    id: 41,
    emoji: "🎭",
    name: "Drama Masks",
    meaning: "Represents theater, acting, or emotions.",
  },
  {
    id: 42,
    emoji: "🦄",
    name: "Unicorn",
    meaning: "Represents uniqueness or something rare.",
  },
  {
    id: 43,
    emoji: "☕",
    name: "Coffee",
    meaning: "Symbolizes caffeine, energy, or a morning ritual.",
  },
  {
    id: 44,
    emoji: "🍀",
    name: "Four-Leaf Clover",
    meaning: "Represents luck and good fortune.",
  },
  {
    id: 45,
    emoji: "🚦",
    name: "Traffic Light",
    meaning: "Represents rules or stopping and going.",
  },
  {
    id: 46,
    emoji: "📚",
    name: "Books",
    meaning: "Symbolizes education, learning, or knowledge.",
  },
  {
    id: 47,
    emoji: "💡",
    name: "Light Bulb",
    meaning: "Represents an idea or innovation.",
  },
  {
    id: 48,
    emoji: "🖥️",
    name: "Computer",
    meaning: "Represents technology, programming, or IT.",
  },
  {
    id: 49,
    emoji: "🛠️",
    name: "Hammer and Wrench",
    meaning: "Symbolizes fixing or engineering.",
  },
  {
    id: 50,
    emoji: "🎮",
    name: "Video Game",
    meaning: "Represents gaming or e-sports.",
  },
  {
    id: 51,
    emoji: "📝",
    name: "Notepad",
    meaning: "Symbolizes writing, notes, or documentation.",
  },
  {
    id: 52,
    emoji: "💸",
    name: "Money Flying",
    meaning: "Represents financial transactions or spending.",
  },
  {
    id: 53,
    emoji: "🌟",
    name: "Glowing Star",
    meaning: "Represents excellence or fame.",
  },
  {
    id: 54,
    emoji: "🚁",
    name: "Helicopter",
    meaning: "Symbolizes emergency transport or VIP travel.",
  },
  {
    id: 55,
    emoji: "🎻",
    name: "Violin",
    meaning: "Represents classical music or sadness.",
  },
  {
    id: 56,
    emoji: "🧩",
    name: "Puzzle Piece",
    meaning: "Symbolizes problem-solving or autism awareness.",
  },
  {
    id: 57,
    emoji: "📢",
    name: "Loudspeaker",
    meaning: "Represents announcements or warnings.",
  },
  {
    id: 58,
    emoji: "📅",
    name: "Calendar",
    meaning: "Symbolizes dates, events, or scheduling.",
  },
  {
    id: 59,
    emoji: "⚽",
    name: "Soccer Ball",
    meaning: "Represents sports and football culture.",
  },
  {
    id: 60,
    emoji: "🚲",
    name: "Bicycle",
    meaning: "Symbolizes eco-friendly transport and fitness.",
  },
];

export default emojipedia;
